package com.videoPlatform.model;
// Generated 2016-12-27 14:58:57 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * TblComment generated by hbm2java
 */
@Entity
@Table(name = "tbl_comment", catalog = "videoplatform")
public class TblComment implements java.io.Serializable {

	private String commentId;
	private TblVideo tblVideo;
	private TblUser tblUser;
	private TblComment tblComment;
	private Date commentCommentTimestamps;
	@JsonIgnore
	private Set<TblComment> tblComments = new HashSet<TblComment>(0);

	public TblComment() {
	}

	public TblComment(String commentId) {
		this.commentId = commentId;
	}

	public TblComment(String commentId, TblVideo tblVideo, TblUser tblUser, TblComment tblComment,
			Date commentCommentTimestamps, Set<TblComment> tblComments) {
		this.commentId = commentId;
		this.tblVideo = tblVideo;
		this.tblUser = tblUser;
		this.tblComment = tblComment;
		this.commentCommentTimestamps = commentCommentTimestamps;
		this.tblComments = tblComments;
	}

	@Id

	@Column(name = "comment_ID", unique = true, nullable = false)
	public String getCommentId() {
		return this.commentId;
	}

	public void setCommentId(String commentId) {
		this.commentId = commentId;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "video_ID")
	public TblVideo getTblVideo() {
		return this.tblVideo;
	}

	public void setTblVideo(TblVideo tblVideo) {
		this.tblVideo = tblVideo;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "user_ID")
	public TblUser getTblUser() {
		return this.tblUser;
	}

	public void setTblUser(TblUser tblUser) {
		this.tblUser = tblUser;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "comment_parentID")
	public TblComment getTblComment() {
		return this.tblComment;
	}

	public void setTblComment(TblComment tblComment) {
		this.tblComment = tblComment;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "comment_commentTimestamps", length = 19)
	public Date getCommentCommentTimestamps() {
		return this.commentCommentTimestamps;
	}

	public void setCommentCommentTimestamps(Date commentCommentTimestamps) {
		this.commentCommentTimestamps = commentCommentTimestamps;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tblComment")
	public Set<TblComment> getTblComments() {
		return this.tblComments;
	}

	public void setTblComments(Set<TblComment> tblComments) {
		this.tblComments = tblComments;
	}

}
