package com.videoPlatform.model;
// Generated 2017-1-15 13:56:31 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * TblDatadictionary generated by hbm2java
 */
@Entity
@Table(name = "tbl_datadictionary", catalog = "videoplatform")
public class TblDatadictionary implements java.io.Serializable {

	private String dataDictionaryId;
	private String dataDictionaryKey;
	private String dataDictionaryValue;
	private String dataDictionaryDescription;
	private Set<TblUserlog> tblUserlogs = new HashSet<TblUserlog>(0);

	public TblDatadictionary() {
	}

	public TblDatadictionary(String dataDictionaryId) {
		this.dataDictionaryId = dataDictionaryId;
	}

	public TblDatadictionary(String dataDictionaryId, String dataDictionaryKey, String dataDictionaryValue,
			String dataDictionaryDescription, Set<TblUserlog> tblUserlogs) {
		this.dataDictionaryId = dataDictionaryId;
		this.dataDictionaryKey = dataDictionaryKey;
		this.dataDictionaryValue = dataDictionaryValue;
		this.dataDictionaryDescription = dataDictionaryDescription;
		this.tblUserlogs = tblUserlogs;
	}

	@Id

	@Column(name = "dataDictionary_ID", unique = true, nullable = false)
	public String getDataDictionaryId() {
		return this.dataDictionaryId;
	}

	public void setDataDictionaryId(String dataDictionaryId) {
		this.dataDictionaryId = dataDictionaryId;
	}

	@Column(name = "dataDictionary_key")
	public String getDataDictionaryKey() {
		return this.dataDictionaryKey;
	}

	public void setDataDictionaryKey(String dataDictionaryKey) {
		this.dataDictionaryKey = dataDictionaryKey;
	}

	@Column(name = "dataDictionary_value")
	public String getDataDictionaryValue() {
		return this.dataDictionaryValue;
	}

	public void setDataDictionaryValue(String dataDictionaryValue) {
		this.dataDictionaryValue = dataDictionaryValue;
	}

	@Column(name = "dataDictionary_description")
	public String getDataDictionaryDescription() {
		return this.dataDictionaryDescription;
	}

	public void setDataDictionaryDescription(String dataDictionaryDescription) {
		this.dataDictionaryDescription = dataDictionaryDescription;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tblDatadictionary")
	@JsonIgnore
	public Set<TblUserlog> getTblUserlogs() {
		return this.tblUserlogs;
	}

	public void setTblUserlogs(Set<TblUserlog> tblUserlogs) {
		this.tblUserlogs = tblUserlogs;
	}

}
