package com.videoPlatform.model;
// Generated 2016-12-27 14:58:57 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * TblDatadictionary generated by hbm2java
 */
@Entity
@Table(name = "tbl_datadictionary", catalog = "videoplatform")
public class TblDatadictionary implements java.io.Serializable {

	private String dataDictionaryId;
	private String dataDictionaryKey;
	private String dataDictionaryValue;
	private String dataDictionaryName;
	private String dataDictionaryDescription;
	private String dataDictionaryParam1;
	private String dataDictionaryParam2;
	@JsonIgnore
	private Set<TblUserlog> tblUserlogs = new HashSet<TblUserlog>(0);
	@JsonIgnore
	private Set<TblVideo> tblVideos = new HashSet<TblVideo>(0);
	@JsonIgnore
	private Set<TblPermission> tblPermissionsForPermissionOperationId = new HashSet<TblPermission>(0);
	@JsonIgnore
	private Set<TblPermission> tblPermissionsForPermissionResourceId = new HashSet<TblPermission>(0);

	public TblDatadictionary() {
	}

	public TblDatadictionary(String dataDictionaryId) {
		this.dataDictionaryId = dataDictionaryId;
	}

	public TblDatadictionary(String dataDictionaryId, String dataDictionaryKey, String dataDictionaryValue,
			String dataDictionaryName, String dataDictionaryDescription, String dataDictionaryParam1,
			String dataDictionaryParam2, Set<TblUserlog> tblUserlogs, Set<TblVideo> tblVideos,
			Set<TblPermission> tblPermissionsForPermissionOperationId,
			Set<TblPermission> tblPermissionsForPermissionResourceId) {
		this.dataDictionaryId = dataDictionaryId;
		this.dataDictionaryKey = dataDictionaryKey;
		this.dataDictionaryValue = dataDictionaryValue;
		this.dataDictionaryName = dataDictionaryName;
		this.dataDictionaryDescription = dataDictionaryDescription;
		this.dataDictionaryParam1 = dataDictionaryParam1;
		this.dataDictionaryParam2 = dataDictionaryParam2;
		this.tblUserlogs = tblUserlogs;
		this.tblVideos = tblVideos;
		this.tblPermissionsForPermissionOperationId = tblPermissionsForPermissionOperationId;
		this.tblPermissionsForPermissionResourceId = tblPermissionsForPermissionResourceId;
	}

	@Id

	@Column(name = "dataDictionary_ID", unique = true, nullable = false)
	public String getDataDictionaryId() {
		return this.dataDictionaryId;
	}

	public void setDataDictionaryId(String dataDictionaryId) {
		this.dataDictionaryId = dataDictionaryId;
	}

	@Column(name = "dataDictionary_key")
	public String getDataDictionaryKey() {
		return this.dataDictionaryKey;
	}

	public void setDataDictionaryKey(String dataDictionaryKey) {
		this.dataDictionaryKey = dataDictionaryKey;
	}

	@Column(name = "dataDictionary_value", length = 255)
	public String getDataDictionaryValue() {
		return this.dataDictionaryValue;
	}

	public void setDataDictionaryValue(String dataDictionaryValue) {
		this.dataDictionaryValue = dataDictionaryValue;
	}

	@Column(name = "dataDictionary_name")
	public String getDataDictionaryName() {
		return this.dataDictionaryName;
	}

	public void setDataDictionaryName(String dataDictionaryName) {
		this.dataDictionaryName = dataDictionaryName;
	}

	@Column(name = "dataDictionary_description")
	public String getDataDictionaryDescription() {
		return this.dataDictionaryDescription;
	}

	public void setDataDictionaryDescription(String dataDictionaryDescription) {
		this.dataDictionaryDescription = dataDictionaryDescription;
	}

	@Column(name = "dataDictionary_param1")
	public String getDataDictionaryParam1() {
		return this.dataDictionaryParam1;
	}

	public void setDataDictionaryParam1(String dataDictionaryParam1) {
		this.dataDictionaryParam1 = dataDictionaryParam1;
	}

	@Column(name = "dataDictionary_param2")
	public String getDataDictionaryParam2() {
		return this.dataDictionaryParam2;
	}

	public void setDataDictionaryParam2(String dataDictionaryParam2) {
		this.dataDictionaryParam2 = dataDictionaryParam2;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tblDatadictionary")
	public Set<TblUserlog> getTblUserlogs() {
		return this.tblUserlogs;
	}

	public void setTblUserlogs(Set<TblUserlog> tblUserlogs) {
		this.tblUserlogs = tblUserlogs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tblDatadictionary")
	public Set<TblVideo> getTblVideos() {
		return this.tblVideos;
	}

	public void setTblVideos(Set<TblVideo> tblVideos) {
		this.tblVideos = tblVideos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tblDatadictionaryByPermissionOperationId")
	public Set<TblPermission> getTblPermissionsForPermissionOperationId() {
		return this.tblPermissionsForPermissionOperationId;
	}

	public void setTblPermissionsForPermissionOperationId(Set<TblPermission> tblPermissionsForPermissionOperationId) {
		this.tblPermissionsForPermissionOperationId = tblPermissionsForPermissionOperationId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tblDatadictionaryByPermissionResourceId")
	public Set<TblPermission> getTblPermissionsForPermissionResourceId() {
		return this.tblPermissionsForPermissionResourceId;
	}

	public void setTblPermissionsForPermissionResourceId(Set<TblPermission> tblPermissionsForPermissionResourceId) {
		this.tblPermissionsForPermissionResourceId = tblPermissionsForPermissionResourceId;
	}

}
