package com.videoPlatform.model;
// Generated 2016-12-27 14:58:57 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * TblDatadictionary generated by hbm2java
 */
@Entity
@Table(name = "tbl_datadictionary", catalog = "videoplatform")
public class TblDatadictionary implements java.io.Serializable {

	@Id
	@Column(name = "dataDictionary_ID", unique = true, nullable = false)
	private String dataDictionaryId;
	private String dataDictionaryKey;
	private String dataDictionaryValue;
	private String dataDictionaryDescription;
	@JsonIgnore
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tblDatadictionary")
	private Set<TblUserlog> tblUserlogs = new HashSet<TblUserlog>(0);

	public TblDatadictionary() {
	}

	public TblDatadictionary(String dataDictionaryId) {
		this.dataDictionaryId = dataDictionaryId;
	}

	public TblDatadictionary(String dataDictionaryId, String dataDictionaryKey, String dataDictionaryValue,
			String dataDictionaryDescription, Set<TblUserlog> tblUserlogs) {
		super();
		this.dataDictionaryId = dataDictionaryId;
		this.dataDictionaryKey = dataDictionaryKey;
		this.dataDictionaryValue = dataDictionaryValue;
		this.dataDictionaryDescription = dataDictionaryDescription;
		this.tblUserlogs = tblUserlogs;
	}

	public String getDataDictionaryId() {
		return dataDictionaryId;
	}

	public void setDataDictionaryId(String dataDictionaryId) {
		this.dataDictionaryId = dataDictionaryId;
	}

	public String getDataDictionaryKey() {
		return dataDictionaryKey;
	}

	public void setDataDictionaryKey(String dataDictionaryKey) {
		this.dataDictionaryKey = dataDictionaryKey;
	}

	public String getDataDictionaryValue() {
		return dataDictionaryValue;
	}

	public void setDataDictionaryValue(String dataDictionaryValue) {
		this.dataDictionaryValue = dataDictionaryValue;
	}

	public String getDataDictionaryDescription() {
		return dataDictionaryDescription;
	}

	public void setDataDictionaryDescription(String dataDictionaryDescription) {
		this.dataDictionaryDescription = dataDictionaryDescription;
	}

	public Set<TblUserlog> getTblUserlogs() {
		return tblUserlogs;
	}

	public void setTblUserlogs(Set<TblUserlog> tblUserlogs) {
		this.tblUserlogs = tblUserlogs;
	}

	

}
