package com.videoPlatform.model;
// Generated 2017-1-15 13:56:31 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * TblOperation generated by hbm2java
 */
@Entity
@Table(name = "tbl_operation", catalog = "videoplatform")
public class TblOperation implements java.io.Serializable {

	private String operationId;
	private String operationName;
	private String operationValue;
	private Set<TblPermission> tblPermissions = new HashSet<TblPermission>(0);

	public TblOperation() {
	}

	public TblOperation(String operationId) {
		this.operationId = operationId;
	}

	public TblOperation(String operationId, String operationName, String operationValue,
			Set<TblPermission> tblPermissions) {
		this.operationId = operationId;
		this.operationName = operationName;
		this.operationValue = operationValue;
		this.tblPermissions = tblPermissions;
	}

	@Id

	@Column(name = "operation_ID", unique = true, nullable = false)
	public String getOperationId() {
		return this.operationId;
	}

	public void setOperationId(String operationId) {
		this.operationId = operationId;
	}

	@Column(name = "operation_Name")
	public String getOperationName() {
		return this.operationName;
	}

	public void setOperationName(String operationName) {
		this.operationName = operationName;
	}

	@Column(name = "operation_value")
	public String getOperationValue() {
		return this.operationValue;
	}

	public void setOperationValue(String operationValue) {
		this.operationValue = operationValue;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tblOperation")
	@JsonIgnore
	public Set<TblPermission> getTblPermissions() {
		return this.tblPermissions;
	}

	public void setTblPermissions(Set<TblPermission> tblPermissions) {
		this.tblPermissions = tblPermissions;
	}

}
