package com.videoPlatform.model;
// Generated 2016-12-27 14:58:57 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * TblPermission generated by hbm2java
 */
@Entity
@Table(name = "tbl_permission", catalog = "videoplatform")
public class TblPermission implements java.io.Serializable {

	private String permissionId;
	private TblDatadictionary tblDatadictionaryByPermissionResourceId;
	private TblRole tblRole;
	private TblDatadictionary tblDatadictionaryByPermissionOperationId;

	public TblPermission() {
	}

	public TblPermission(String permissionId) {
		this.permissionId = permissionId;
	}

	public TblPermission(String permissionId, TblDatadictionary tblDatadictionaryByPermissionResourceId,
			TblRole tblRole, TblDatadictionary tblDatadictionaryByPermissionOperationId) {
		this.permissionId = permissionId;
		this.tblDatadictionaryByPermissionResourceId = tblDatadictionaryByPermissionResourceId;
		this.tblRole = tblRole;
		this.tblDatadictionaryByPermissionOperationId = tblDatadictionaryByPermissionOperationId;
	}

	@Id

	@Column(name = "permission_ID", unique = true, nullable = false)
	public String getPermissionId() {
		return this.permissionId;
	}

	public void setPermissionId(String permissionId) {
		this.permissionId = permissionId;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "permission_resourceID")
	public TblDatadictionary getTblDatadictionaryByPermissionResourceId() {
		return this.tblDatadictionaryByPermissionResourceId;
	}

	public void setTblDatadictionaryByPermissionResourceId(TblDatadictionary tblDatadictionaryByPermissionResourceId) {
		this.tblDatadictionaryByPermissionResourceId = tblDatadictionaryByPermissionResourceId;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "role_ID")
	public TblRole getTblRole() {
		return this.tblRole;
	}

	public void setTblRole(TblRole tblRole) {
		this.tblRole = tblRole;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "permission_operationID")
	public TblDatadictionary getTblDatadictionaryByPermissionOperationId() {
		return this.tblDatadictionaryByPermissionOperationId;
	}

	public void setTblDatadictionaryByPermissionOperationId(
			TblDatadictionary tblDatadictionaryByPermissionOperationId) {
		this.tblDatadictionaryByPermissionOperationId = tblDatadictionaryByPermissionOperationId;
	}

}
