package com.videoPlatform.model;
// Generated 2016-12-27 14:58:57 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * TblPermission generated by hbm2java
 */
@Entity
@Table(name = "tbl_permission", catalog = "videoplatform")
public class TblPermission implements java.io.Serializable {

	@Id
	@Column(name = "permission_ID", unique = true, nullable = false)
	private String permissionId;
	private String permissionDescription;
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "permission_resourceID")
	private TblResource tblResource;
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "permission_operationID")
	private TblOperation tblOperation;
	@JsonIgnore
	private Set<TblRolePermissionRelation> tblRolePermissionRelations = new HashSet<TblRolePermissionRelation>(0);

	public TblPermission() {
	}

	public TblPermission(String permissionId) {
		this.permissionId = permissionId;
	}

	public TblPermission(String permissionId, String permissionDescription, TblResource tblResource,
			TblOperation tblOperation, Set<TblRolePermissionRelation> tblRolePermissionRelations) {
		super();
		this.permissionId = permissionId;
		this.permissionDescription = permissionDescription;
		this.tblResource = tblResource;
		this.tblOperation = tblOperation;
		this.tblRolePermissionRelations = tblRolePermissionRelations;
	}

	
	public String getPermissionId() {
		return this.permissionId;
	}

	public void setPermissionId(String permissionId) {
		this.permissionId = permissionId;
	}

	public TblResource getTblResource() {
		return tblResource;
	}

	public void setTblResource(TblResource tblResource) {
		this.tblResource = tblResource;
	}

	public TblOperation getTblOperation() {
		return tblOperation;
	}

	public void setTblOperation(TblOperation tblOperation) {
		this.tblOperation = tblOperation;
	}
	

	public Set<TblRolePermissionRelation> getTblRolePermissionRelations() {
		return tblRolePermissionRelations;
	}

	public void setTblRolePermissionRelations(Set<TblRolePermissionRelation> tblRolePermissionRelations) {
		this.tblRolePermissionRelations = tblRolePermissionRelations;
	}

	public String getPermissionDescription() {
		return permissionDescription;
	}

	public void setPermissionDescription(String permissionDescription) {
		this.permissionDescription = permissionDescription;
	}

	
	
}
