package com.videoPlatform.model;
// Generated 2017-1-15 13:56:31 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * TblPermission generated by hbm2java
 */
@Entity
@Table(name = "tbl_permission", catalog = "videoplatform")
public class TblPermission implements java.io.Serializable {

	private String permissionId;
	private TblResource tblResource;
	private TblOperation tblOperation;
	private String permissionDescription;
	private Set<TblRolePermissionRelation> tblRolepermissionrelations = new HashSet<TblRolePermissionRelation>(0);

	public TblPermission() {
	}

	public TblPermission(String permissionId) {
		this.permissionId = permissionId;
	}

	public TblPermission(String permissionId, TblResource tblResource, TblOperation tblOperation,
			String permissionDescription, Set<TblRolePermissionRelation> tblRolepermissionrelations) {
		this.permissionId = permissionId;
		this.tblResource = tblResource;
		this.tblOperation = tblOperation;
		this.permissionDescription = permissionDescription;
		this.tblRolepermissionrelations = tblRolepermissionrelations;
	}

	@Id

	@Column(name = "permission_ID", unique = true, nullable = false)
	public String getPermissionId() {
		return this.permissionId;
	}

	public void setPermissionId(String permissionId) {
		this.permissionId = permissionId;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "permission_resourceID")
	public TblResource getTblResource() {
		return this.tblResource;
	}

	public void setTblResource(TblResource tblResource) {
		this.tblResource = tblResource;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "permission_operationID")
	public TblOperation getTblOperation() {
		return this.tblOperation;
	}

	public void setTblOperation(TblOperation tblOperation) {
		this.tblOperation = tblOperation;
	}

	@Column(name = "permission_description")
	public String getPermissionDescription() {
		return this.permissionDescription;
	}

	public void setPermissionDescription(String permissionDescription) {
		this.permissionDescription = permissionDescription;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tblPermission")
	@JsonIgnore
	public Set<TblRolePermissionRelation> getTblRolepermissionrelations() {
		return this.tblRolepermissionrelations;
	}

	public void setTblRolepermissionrelations(Set<TblRolePermissionRelation> tblRolepermissionrelations) {
		this.tblRolepermissionrelations = tblRolepermissionrelations;
	}

}
