package com.videoPlatform.model;
// Generated 2017-1-15 13:56:31 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * TblResource generated by hbm2java
 */
@Entity
@Table(name = "tbl_resource", catalog = "videoplatform")
public class TblResource implements java.io.Serializable {

	private String resourceId;
	private String resourceDescription;
	private String resourceUri;
	private String resourceType;
	private String resourceName;
	private String resourceValue;
	private Set<TblPermission> tblPermissions = new HashSet<TblPermission>(0);

	public TblResource() {
	}

	public TblResource(String resourceId) {
		this.resourceId = resourceId;
	}

	public TblResource(String resourceId, String resourceDescription, String resourceUri, String resourceType,
			String resourceName, String resourceValue, Set<TblPermission> tblPermissions) {
		this.resourceId = resourceId;
		this.resourceDescription = resourceDescription;
		this.resourceUri = resourceUri;
		this.resourceType = resourceType;
		this.resourceName = resourceName;
		this.resourceValue = resourceValue;
		this.tblPermissions = tblPermissions;
	}

	@Id

	@Column(name = "resource_ID", unique = true, nullable = false)
	public String getResourceId() {
		return this.resourceId;
	}

	public void setResourceId(String resourceId) {
		this.resourceId = resourceId;
	}

	@Column(name = "resource_description")
	public String getResourceDescription() {
		return this.resourceDescription;
	}

	public void setResourceDescription(String resourceDescription) {
		this.resourceDescription = resourceDescription;
	}

	@Column(name = "resource_URI")
	public String getResourceUri() {
		return this.resourceUri;
	}

	public void setResourceUri(String resourceUri) {
		this.resourceUri = resourceUri;
	}

	@Column(name = "resource_type")
	public String getResourceType() {
		return this.resourceType;
	}

	public void setResourceType(String resourceType) {
		this.resourceType = resourceType;
	}

	@Column(name = "resourceName")
	public String getResourceName() {
		return this.resourceName;
	}

	public void setResourceName(String resourceName) {
		this.resourceName = resourceName;
	}

	@Column(name = "resourceValue")
	public String getResourceValue() {
		return this.resourceValue;
	}

	public void setResourceValue(String resourceValue) {
		this.resourceValue = resourceValue;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tblResource")
	@JsonIgnore
	public Set<TblPermission> getTblPermissions() {
		return this.tblPermissions;
	}

	public void setTblPermissions(Set<TblPermission> tblPermissions) {
		this.tblPermissions = tblPermissions;
	}

}
