package com.videoPlatform.model;
// Generated 2017-1-15 13:56:31 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * TblRole generated by hbm2java
 */
@Entity
@Table(name = "tbl_role", catalog = "videoplatform")
public class TblRole implements java.io.Serializable {

	private String roleId;
	private String roleName;
	private Set<TblRolePermissionRelation> tblRolepermissionrelations = new HashSet<TblRolePermissionRelation>(0);
	private Set<TblUser> tblUsers = new HashSet<TblUser>(0);

	public TblRole() {
	}

	public TblRole(String roleId) {
		this.roleId = roleId;
	}

	public TblRole(String roleId, String roleName, Set<TblRolePermissionRelation> tblRolepermissionrelations,
			Set<TblUser> tblUsers) {
		this.roleId = roleId;
		this.roleName = roleName;
		this.tblRolepermissionrelations = tblRolepermissionrelations;
		this.tblUsers = tblUsers;
	}

	@Id

	@Column(name = "role_ID", unique = true, nullable = false)
	public String getRoleId() {
		return this.roleId;
	}

	public void setRoleId(String roleId) {
		this.roleId = roleId;
	}

	@Column(name = "role_Name")
	public String getRoleName() {
		return this.roleName;
	}

	public void setRoleName(String roleName) {
		this.roleName = roleName;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tblRole")
	@JsonIgnore
	public Set<TblRolePermissionRelation> getTblRolepermissionrelations() {
		return this.tblRolepermissionrelations;
	}

	public void setTblRolepermissionrelations(Set<TblRolePermissionRelation> tblRolepermissionrelations) {
		this.tblRolepermissionrelations = tblRolepermissionrelations;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tblRole")
	@JsonIgnore
	public Set<TblUser> getTblUsers() {
		return this.tblUsers;
	}

	public void setTblUsers(Set<TblUser> tblUsers) {
		this.tblUsers = tblUsers;
	}

}
