package com.videoPlatform.model;
// Generated 2017-1-15 13:56:31 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * TblRolepermissionrelation generated by hbm2java
 */
@Entity
@Table(name = "tbl_rolepermissionrelation", catalog = "videoplatform")
public class TblRolePermissionRelation implements java.io.Serializable {

	private String rolePermissionRelationId;
	private TblRole tblRole;
	private TblPermission tblPermission;

	public TblRolePermissionRelation() {
	}

	public TblRolePermissionRelation(String rolePermissionRelationId) {
		this.rolePermissionRelationId = rolePermissionRelationId;
	}

	public TblRolePermissionRelation(String rolePermissionRelationId, TblRole tblRole, TblPermission tblPermission) {
		this.rolePermissionRelationId = rolePermissionRelationId;
		this.tblRole = tblRole;
		this.tblPermission = tblPermission;
	}

	@Id

	@Column(name = "rolePermissionRelation_ID", unique = true, nullable = false)
	public String getRolePermissionRelationId() {
		return this.rolePermissionRelationId;
	}

	public void setRolePermissionRelationId(String rolePermissionRelationId) {
		this.rolePermissionRelationId = rolePermissionRelationId;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "rolePermissionRelation_roleID")
	public TblRole getTblRole() {
		return this.tblRole;
	}

	public void setTblRole(TblRole tblRole) {
		this.tblRole = tblRole;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "rolePermissionRelation_permissionID")
	public TblPermission getTblPermission() {
		return this.tblPermission;
	}

	public void setTblPermission(TblPermission tblPermission) {
		this.tblPermission = tblPermission;
	}

}
