package com.videoPlatform.model;
// Generated 2016-12-27 14:58:57 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * TblRole generated by hbm2java
 */
@Entity
@Table(name = "tbl_role", catalog = "videoplatform")
public class TblRole implements java.io.Serializable {

	private String roleId;
	private String roleName;
	@JsonIgnore
	private Set<TblUser> tblUsers = new HashSet<TblUser>(0);
	@JsonIgnore
	private Set<TblPermission> tblPermissions = new HashSet<TblPermission>(0);

	public TblRole() {
	}

	public TblRole(String roleId) {
		this.roleId = roleId;
	}

	public TblRole(String roleId, String roleName, Set<TblUser> tblUsers, Set<TblPermission> tblPermissions) {
		this.roleId = roleId;
		this.roleName = roleName;
		this.tblUsers = tblUsers;
		this.tblPermissions = tblPermissions;
	}

	@Id

	@Column(name = "role_ID", unique = true, nullable = false)
	public String getRoleId() {
		return this.roleId;
	}

	public void setRoleId(String roleId) {
		this.roleId = roleId;
	}

	@Column(name = "role_Name")
	public String getRoleName() {
		return this.roleName;
	}

	public void setRoleName(String roleName) {
		this.roleName = roleName;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "tblRole")
	public Set<TblUser> getTblUsers() {
		return this.tblUsers;
	}

	public void setTblUsers(Set<TblUser> tblUsers) {
		this.tblUsers = tblUsers;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tblRole")
	public Set<TblPermission> getTblPermissions() {
		return this.tblPermissions;
	}

	public void setTblPermissions(Set<TblPermission> tblPermissions) {
		this.tblPermissions = tblPermissions;
	}

}
