package com.videoPlatform.model;
// Generated 2017-1-15 13:56:31 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * TblTag generated by hbm2java
 */
@Entity
@Table(name = "tbl_tag", catalog = "videoplatform")
public class TblTag implements java.io.Serializable {

	private String tagId;
	private String tagName;
	private String tagCategory;
	private Set<TblVideotagrelation> tblVideotagrelations = new HashSet<TblVideotagrelation>(0);

	public TblTag() {
	}

	public TblTag(String tagId) {
		this.tagId = tagId;
	}

	public TblTag(String tagId, String tagName, String tagCategory, Set<TblVideotagrelation> tblVideotagrelations) {
		this.tagId = tagId;
		this.tagName = tagName;
		this.tagCategory = tagCategory;
		this.tblVideotagrelations = tblVideotagrelations;
	}

	@Id

	@Column(name = "tag_ID", unique = true, nullable = false)
	public String getTagId() {
		return this.tagId;
	}

	public void setTagId(String tagId) {
		this.tagId = tagId;
	}

	@Column(name = "tag_Name")
	public String getTagName() {
		return this.tagName;
	}

	public void setTagName(String tagName) {
		this.tagName = tagName;
	}

	@Column(name = "tag_Category")
	public String getTagCategory() {
		return this.tagCategory;
	}

	public void setTagCategory(String tagCategory) {
		this.tagCategory = tagCategory;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tblTag")
	@JsonIgnore
	public Set<TblVideotagrelation> getTblVideotagrelations() {
		return this.tblVideotagrelations;
	}

	public void setTblVideotagrelations(Set<TblVideotagrelation> tblVideotagrelations) {
		this.tblVideotagrelations = tblVideotagrelations;
	}

}
