package com.videoPlatform.model;
// Generated 2016-12-27 14:58:57 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TblUservideorelation generated by hbm2java
 */
@Entity
@Table(name = "tbl_uservideorelation", catalog = "videoplatform")
public class TblUservideorelation implements java.io.Serializable {

	private String userVideoRelationId;
	private TblVideo tblVideo;
	private TblUser tblUser;
	private String userVideoRelationType;
	private Date userVideoRelationOperationTimestamps;

	public TblUservideorelation() {
	}

	public TblUservideorelation(String userVideoRelationId) {
		this.userVideoRelationId = userVideoRelationId;
	}

	public TblUservideorelation(String userVideoRelationId, TblVideo tblVideo, TblUser tblUser,
			String userVideoRelationType, Date userVideoRelationOperationTimestamps) {
		this.userVideoRelationId = userVideoRelationId;
		this.tblVideo = tblVideo;
		this.tblUser = tblUser;
		this.userVideoRelationType = userVideoRelationType;
		this.userVideoRelationOperationTimestamps = userVideoRelationOperationTimestamps;
	}

	@Id

	@Column(name = "userVideoRelation_ID", unique = true, nullable = false)
	public String getUserVideoRelationId() {
		return this.userVideoRelationId;
	}

	public void setUserVideoRelationId(String userVideoRelationId) {
		this.userVideoRelationId = userVideoRelationId;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "video_ID")
	public TblVideo getTblVideo() {
		return this.tblVideo;
	}

	public void setTblVideo(TblVideo tblVideo) {
		this.tblVideo = tblVideo;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "user_ID")
	public TblUser getTblUser() {
		return this.tblUser;
	}

	public void setTblUser(TblUser tblUser) {
		this.tblUser = tblUser;
	}

	@Column(name = "userVideoRelation_Type")
	public String getUserVideoRelationType() {
		return this.userVideoRelationType;
	}

	public void setUserVideoRelationType(String userVideoRelationType) {
		this.userVideoRelationType = userVideoRelationType;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "userVideoRelation_operationTimestamps", length = 19)
	public Date getUserVideoRelationOperationTimestamps() {
		return this.userVideoRelationOperationTimestamps;
	}

	public void setUserVideoRelationOperationTimestamps(Date userVideoRelationOperationTimestamps) {
		this.userVideoRelationOperationTimestamps = userVideoRelationOperationTimestamps;
	}

}
