package com.videoPlatform.model;
// Generated 2017-1-15 13:56:31 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * TblUserpicture generated by hbm2java
 */
@Entity
@Table(name = "tbl_userpicture", catalog = "videoplatform")
public class TblUserpicture implements java.io.Serializable {

	private String userPictureId;
	private TblVideotagrelation tblVideotagrelation;
	private TblUser tblUser;
	private Integer weightValue;

	public TblUserpicture() {
	}

	public TblUserpicture(String userPictureId) {
		this.userPictureId = userPictureId;
	}

	public TblUserpicture(String userPictureId, TblVideotagrelation tblVideotagrelation, TblUser tblUser,
			Integer weightValue) {
		this.userPictureId = userPictureId;
		this.tblVideotagrelation = tblVideotagrelation;
		this.tblUser = tblUser;
		this.weightValue = weightValue;
	}

	@Id

	@Column(name = "userPicture_ID", unique = true, nullable = false)
	public String getUserPictureId() {
		return this.userPictureId;
	}

	public void setUserPictureId(String userPictureId) {
		this.userPictureId = userPictureId;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "videoTagRelation_ID")
	public TblVideotagrelation getTblVideotagrelation() {
		return this.tblVideotagrelation;
	}

	public void setTblVideotagrelation(TblVideotagrelation tblVideotagrelation) {
		this.tblVideotagrelation = tblVideotagrelation;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "user_ID")
	public TblUser getTblUser() {
		return this.tblUser;
	}

	public void setTblUser(TblUser tblUser) {
		this.tblUser = tblUser;
	}

	@Column(name = "weightValue")
	public Integer getWeightValue() {
		return this.weightValue;
	}

	public void setWeightValue(Integer weightValue) {
		this.weightValue = weightValue;
	}

}
