package com.videoPlatform.model;
// Generated 2016-12-27 14:58:57 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TblUserlog generated by hbm2java
 */
@Entity
@Table(name = "tbl_userlog", catalog = "videoplatform")
public class TblUserlog implements java.io.Serializable {

	private String userLogId;
	private TblUser tblUser;
	private TblDatadictionary tblDatadictionary;
	private Date userLogTimestampsStart;
	private Date userLogTimestampsEnd;
	private String userLogParam1;
	private String userLogParam2;

	public TblUserlog() {
	}

	public TblUserlog(String userLogId) {
		this.userLogId = userLogId;
	}

	public TblUserlog(String userLogId, TblUser tblUser, TblDatadictionary tblDatadictionary,
			Date userLogTimestampsStart, Date userLogTimestampsEnd, String userLogParam1, String userLogParam2) {
		this.userLogId = userLogId;
		this.tblUser = tblUser;
		this.tblDatadictionary = tblDatadictionary;
		this.userLogTimestampsStart = userLogTimestampsStart;
		this.userLogTimestampsEnd = userLogTimestampsEnd;
		this.userLogParam1 = userLogParam1;
		this.userLogParam2 = userLogParam2;
	}

	@Id

	@Column(name = "userLog_ID", unique = true, nullable = false)
	public String getUserLogId() {
		return this.userLogId;
	}

	public void setUserLogId(String userLogId) {
		this.userLogId = userLogId;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "user_ID")
	public TblUser getTblUser() {
		return this.tblUser;
	}

	public void setTblUser(TblUser tblUser) {
		this.tblUser = tblUser;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "userLog_resourceID")
	public TblDatadictionary getTblDatadictionary() {
		return this.tblDatadictionary;
	}

	public void setTblDatadictionary(TblDatadictionary tblDatadictionary) {
		this.tblDatadictionary = tblDatadictionary;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "userLog_timestamps_start", length = 19)
	public Date getUserLogTimestampsStart() {
		return this.userLogTimestampsStart;
	}

	public void setUserLogTimestampsStart(Date userLogTimestampsStart) {
		this.userLogTimestampsStart = userLogTimestampsStart;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "userLog_timestamps_end", length = 19)
	public Date getUserLogTimestampsEnd() {
		return this.userLogTimestampsEnd;
	}

	public void setUserLogTimestampsEnd(Date userLogTimestampsEnd) {
		this.userLogTimestampsEnd = userLogTimestampsEnd;
	}

	@Column(name = "userLog_param1")
	public String getUserLogParam1() {
		return this.userLogParam1;
	}

	public void setUserLogParam1(String userLogParam1) {
		this.userLogParam1 = userLogParam1;
	}

	@Column(name = "userLog_param2")
	public String getUserLogParam2() {
		return this.userLogParam2;
	}

	public void setUserLogParam2(String userLogParam2) {
		this.userLogParam2 = userLogParam2;
	}

}
