package com.videoPlatform.model;
// Generated 2017-1-15 13:56:31 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * TblVideocategory generated by hbm2java
 */
@Entity
@Table(name = "tbl_videocategory", catalog = "videoplatform")
public class TblVideoCategory implements java.io.Serializable {

	private String videoCategoryId;
	private String videoCategoryName;
	private String videoCategroyUrl;
	private Set<TblVideo> tblVideos = new HashSet<TblVideo>(0);

	public TblVideoCategory() {
	}

	public TblVideoCategory(String videoCategoryId) {
		this.videoCategoryId = videoCategoryId;
	}

	public TblVideoCategory(String videoCategoryId, String videoCategoryName, String videoCategroyUrl,
			Set<TblVideo> tblVideos) {
		this.videoCategoryId = videoCategoryId;
		this.videoCategoryName = videoCategoryName;
		this.videoCategroyUrl = videoCategroyUrl;
		this.tblVideos = tblVideos;
	}

	@Id

	@Column(name = "videoCategory_ID", unique = true, nullable = false)
	public String getVideoCategoryId() {
		return this.videoCategoryId;
	}

	public void setVideoCategoryId(String videoCategoryId) {
		this.videoCategoryId = videoCategoryId;
	}

	@Column(name = "videoCategory_Name")
	public String getVideoCategoryName() {
		return this.videoCategoryName;
	}

	public void setVideoCategoryName(String videoCategoryName) {
		this.videoCategoryName = videoCategoryName;
	}

	@Column(name = "videoCategroy_Url")
	public String getVideoCategroyUrl() {
		return this.videoCategroyUrl;
	}

	public void setVideoCategroyUrl(String videoCategroyUrl) {
		this.videoCategroyUrl = videoCategroyUrl;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tblVideocategory")
	@JsonIgnore
	public Set<TblVideo> getTblVideos() {
		return this.tblVideos;
	}

	public void setTblVideos(Set<TblVideo> tblVideos) {
		this.tblVideos = tblVideos;
	}

}
