package com.videoPlatform.model;
// Generated 2016-12-27 14:58:57 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * TblVideo generated by hbm2java
 */
@Entity
@Table(name = "tbl_video", catalog = "videoplatform")
public class TblVideo implements java.io.Serializable {

	@Id
	@Column(name = "video_ID", unique = true, nullable = false)
	private String videoId;
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "user_ID")
	private TblUser tblUser;
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "video_videoCategoryID")
	private TblVideoCategory tblVideoCategory;
	private String videoName;
	private String videoBrand;
	private String videoCountry;
	private String videoIsDownloadable;
	private String videoLanguage;
	private String videoPublishYear;
	private String videoCoverLink;
	private String videoSourceLink;
	private String videoDescription;
	private String videoOriginSource;
	@JsonIgnore
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tblVideo")
	private Set<TblUservideorelation> tblUservideorelations = new HashSet<TblUservideorelation>(0);
	@JsonIgnore
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tblVideo")
	private Set<TblComment> tblComments = new HashSet<TblComment>(0);
	@JsonIgnore
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tblVideo")
	private Set<TblVideotagrelation> tblVideotagrelations = new HashSet<TblVideotagrelation>(0);

	public TblVideo() {
	}

	public TblVideo(String videoId) {
		this.videoId = videoId;
	}

	public TblVideo(String videoId, TblUser tblUser, TblVideoCategory tblVideoCategory, String videoName,
			String videoBrand, String videoCountry, String videoIsDownloadable, String videoLanguage,
			String videoPublishYear, String videoCoverLink, String videoSourceLink, String videoDescription,
			String videoOriginSource, Set<TblUservideorelation> tblUservideorelations, Set<TblComment> tblComments,
			Set<TblVideotagrelation> tblVideotagrelations) {
		super();
		this.videoId = videoId;
		this.tblUser = tblUser;
		this.tblVideoCategory = tblVideoCategory;
		this.videoName = videoName;
		this.videoBrand = videoBrand;
		this.videoCountry = videoCountry;
		this.videoIsDownloadable = videoIsDownloadable;
		this.videoLanguage = videoLanguage;
		this.videoPublishYear = videoPublishYear;
		this.videoCoverLink = videoCoverLink;
		this.videoSourceLink = videoSourceLink;
		this.videoDescription = videoDescription;
		this.videoOriginSource = videoOriginSource;
		this.tblUservideorelations = tblUservideorelations;
		this.tblComments = tblComments;
		this.tblVideotagrelations = tblVideotagrelations;
	}


	public String getVideoId() {
		return this.videoId;
	}

	public void setVideoId(String videoId) {
		this.videoId = videoId;
	}

	public TblUser getTblUser() {
		return this.tblUser;
	}

	public void setTblUser(TblUser tblUser) {
		this.tblUser = tblUser;
	}

	public TblVideoCategory getTblVideoCategory() {
		return tblVideoCategory;
	}

	public void setTblVideoCategory(TblVideoCategory tblVideoCategory) {
		this.tblVideoCategory = tblVideoCategory;
	}

	@Column(name = "video_name")
	public String getVideoName() {
		return this.videoName;
	}

	public void setVideoName(String videoName) {
		this.videoName = videoName;
	}

	@Column(name = "video_brand")
	public String getVideoBrand() {
		return this.videoBrand;
	}

	public void setVideoBrand(String videoBrand) {
		this.videoBrand = videoBrand;
	}

	@Column(name = "video_country")
	public String getVideoCountry() {
		return this.videoCountry;
	}

	public void setVideoCountry(String videoCountry) {
		this.videoCountry = videoCountry;
	}

	@Column(name = "video_isDownloadable")
	public String getVideoIsDownloadable() {
		return this.videoIsDownloadable;
	}

	public void setVideoIsDownloadable(String videoIsDownloadable) {
		this.videoIsDownloadable = videoIsDownloadable;
	}

	@Column(name = "video_language")
	public String getVideoLanguage() {
		return this.videoLanguage;
	}

	public void setVideoLanguage(String videoLanguage) {
		this.videoLanguage = videoLanguage;
	}

	@Column(name = "video_publishYear")
	public String getVideoPublishYear() {
		return this.videoPublishYear;
	}

	public void setVideoPublishYear(String videoPublishYear) {
		this.videoPublishYear = videoPublishYear;
	}

	@Column(name = "video_coverLink")
	public String getVideoCoverLink() {
		return this.videoCoverLink;
	}

	public void setVideoCoverLink(String videoCoverLink) {
		this.videoCoverLink = videoCoverLink;
	}

	@Column(name = "video_sourceLink")
	public String getVideoSourceLink() {
		return this.videoSourceLink;
	}

	public void setVideoSourceLink(String videoSourceLink) {
		this.videoSourceLink = videoSourceLink;
	}

	@Column(name = "video_description")
	public String getVideoDescription() {
		return this.videoDescription;
	}

	public void setVideoDescription(String videoDescription) {
		this.videoDescription = videoDescription;
	}

	@Column(name = "video_originSource")
	public String getVideoOriginSource() {
		return this.videoOriginSource;
	}

	public void setVideoOriginSource(String videoOriginSource) {
		this.videoOriginSource = videoOriginSource;
	}


	public Set<TblUservideorelation> getTblUservideorelations() {
		return this.tblUservideorelations;
	}

	public void setTblUservideorelations(Set<TblUservideorelation> tblUservideorelations) {
		this.tblUservideorelations = tblUservideorelations;
	}


	public Set<TblComment> getTblComments() {
		return this.tblComments;
	}

	public void setTblComments(Set<TblComment> tblComments) {
		this.tblComments = tblComments;
	}


	public Set<TblVideotagrelation> getTblVideotagrelations() {
		return this.tblVideotagrelations;
	}

	public void setTblVideotagrelations(Set<TblVideotagrelation> tblVideotagrelations) {
		this.tblVideotagrelations = tblVideotagrelations;
	}

}
